language: node_js
node_js:
  - "10"

branches:
  only:
    - master

before_script:
  - touch ./functions/secret.json
  - echo $SENDGRID_API_KEY
  - echo {\"API_KEY\" : \"$SENDGRID_API_KEY\"} > ./functions/secret.json
  - cat ./functions/secret.json
  - npm install -g firebase-tools
  - npm install
  - npm --prefix ./functions install

script:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change
