language: node_js
node_js:
  - "10"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools

script:
  - npm install
  - npm --prefix ./functions install
  - echo {\"API_KEY\" : \"$SENDGRID_API_KEY\"} > functions/secret.json
  - cat functions/secret.json

after_success:
  - firebase deploy --token $FIREBASE_TOKEN
