language: node_js
node_js:
  - "10"

cache:
  directories:
    - node_modules
    - functions/node_modules

branches:
  only:
    - master

before_script:
  - touch ./functions/secret.json
  - echo '{"API_KEY":"'$SENDGRID_API_KEY'"}' > ./functions/secret.json
  - npm install -g firebase-tools
  - npm install
  - npm --prefix ./functions install

script:
  - firebase deploy --token $FIREBASE_TOKEN
