language: node_js
node_js:
  - "10"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools

script:
  - npm install

after_success:
  - firebase deploy --token $FIREBASE_TOKEN
